"""Enemy registry — auto-generated by tools/build_enemy_registry.py.

Each SLOT_N_PACKAGES entry:
  gfx_label: (data_labels, palette_rom_offset_in_hacked_rom)

gfx/data labels are resolved at generation time via warioland3.sym
(embedded elsewhere). The palette offset points into the hacked ROM
(vanilla ROM + bsdiff); the apworld reads 8 bytes from there at gen
time, so no vanilla palette bytes are shipped with the apworld.
"""

SLOT_0_PACKAGES = {
    "HaridamaGfx": {"gfx_addr": 0x624a, "data_addrs": [0x45bb], "palette_offset": 0x065798},
    "MadSciensteinGfx": {"gfx_addr": 0x53a5, "data_addrs": [0x451b], "palette_offset": 0x065608},
    "MizuuoGfx": {"gfx_addr": 0x45a5, "data_addrs": [0x44a3], "palette_offset": 0x06543d},
    "Moon1Gfx": {"gfx_addr": 0x5b1c, "data_addrs": [0x4563], "palette_offset": 0x0656d2},
    "RoboMouse1Gfx": {"gfx_addr": 0x5eac, "data_addrs": [0x45ab], "palette_offset": 0x065969},
    "SilkyGfx": {"gfx_addr": 0x490d, "data_addrs": [0x44bb], "palette_offset": 0x065375},
    "SnakeGfx": {"gfx_addr": 0x4c59, "data_addrs": [0x44d3], "palette_offset": 0x065507},
    "SpearheadGfx": {"gfx_addr": 0x4000, "data_addrs": [0x4413], "palette_offset": 0x065342},
    "StoveGfx": {"gfx_addr": 0x68ae, "data_addrs": [0x444b], "palette_offset": 0x065b3c},
    "Sun1Gfx": {"gfx_addr": 0x5754, "data_addrs": [0x455b], "palette_offset": 0x0656a1},
}

SLOT_1_PACKAGES = {
    "ApplebyGfx": {"gfx_addr": 0x4e29, "data_addrs": [0x44db], "palette_offset": 0x0655a8},
    "CountRichtertoffenGfx": {"gfx_addr": 0x4327, "data_addrs": [0x445b], "palette_offset": 0x065317},
    "HammerBotGfx": {"gfx_addr": 0x514c, "data_addrs": [0x450b], "palette_offset": 0x0655db},
    "KushimushiGfx": {"gfx_addr": 0x4956, "data_addrs": [0x4493, 0x449b], "palette_offset": 0x065418},
    "Moon2Gfx": {"gfx_addr": 0x5b1f, "data_addrs": [0x4563], "palette_offset": 0x0656da},
    "ParaGoomGfx": {"gfx_addr": 0x4637, "data_addrs": [0x446b], "palette_offset": 0x06550f},
    "PneumoGfx": {"gfx_addr": 0x547a, "data_addrs": [0x452b], "palette_offset": 0x065643},
    "RoboMouse2Gfx": {"gfx_addr": 0x5de3, "data_addrs": [0x45ab], "palette_offset": 0x065971},
    "Sun2Gfx": {"gfx_addr": 0x578c, "data_addrs": [0x455b], "palette_offset": 0x0656a9},
    "WebberGfx": {"gfx_addr": 0x4000, "data_addrs": [0x4423], "palette_offset": 0x065575},
}

SLOT_2_PACKAGES = {
    "DoughnuteerGfx": {"gfx_addr": 0x45b3, "data_addrs": [0x4473], "palette_offset": 0x06531f},
    "FireGfx": {"gfx_addr": 0x65ac, "data_addrs": [0x4703, 0x4543], "palette_offset": 0x066045},
    "HandGfx": {"gfx_addr": 0x567b, "data_addrs": [0x4573], "palette_offset": 0x065748},
    "HebariiGfx": {"gfx_addr": 0x4327, "data_addrs": [0x4463], "palette_offset": 0x065eab},
    "KobattoGfx": {"gfx_addr": 0x545b, "data_addrs": [0x456b], "palette_offset": 0x0657db},
    "SpearBotGfx": {"gfx_addr": 0x4dc2, "data_addrs": [0x454b], "palette_offset": 0x0655e3},
    "TadpoleGfx": {"gfx_addr": 0x62cc, "data_addrs": [0x46c3], "palette_offset": 0x065ede},
    "ZombieGfx": {"gfx_addr": 0x4a8a, "data_addrs": [0x453b], "palette_offset": 0x06554a},
}

SLOT_3_PACKAGES = {
    "BeamBotGfx": {"gfx_addr": 0x4610, "data_addrs": [0x4553], "palette_offset": 0x065327},
    "BrrrBearGfx": {"gfx_addr": 0x54ea, "data_addrs": [0x4583], "palette_offset": 0x0659e7},
    "FireBotGfx": {"gfx_addr": 0x4234, "data_addrs": [0x4543], "palette_offset": 0x06551f},
    "NobiiruGfx": {"gfx_addr": 0x5dec, "data_addrs": [0x4673, 0x467b], "palette_offset": 0x0658ea},
    "TeruteruGfx": {"gfx_addr": 0x4ee3, "data_addrs": [0x4513], "palette_offset": 0x065620},
    "TogebaGfx": {"gfx_addr": 0x5861, "data_addrs": [0x45b3], "palette_offset": 0x0659b4},
    "TorchGfx": {"gfx_addr": 0x4000, "data_addrs": [0x442b], "palette_offset": 0x06535a},
    "WaterDropGfx": {"gfx_addr": 0x5d44, "data_addrs": [0x465b], "palette_offset": 0x0657e3},
}
