"""Enemy registry — auto-generated by tools/build_enemy_registry.py.

Each SLOT_N_PACKAGES entry:
  gfx_label: (data_labels, palette_rom_offset_in_hacked_rom)

gfx/data labels are resolved at generation time via warioland3.sym
(embedded elsewhere). The palette offset points into the hacked ROM
(vanilla ROM + bsdiff); the apworld reads 8 bytes from there at gen
time, so no vanilla palette bytes are shipped with the apworld.
"""

SLOT_0_PACKAGES = {
    "HaridamaGfx": {"gfx_addr": 0x624a, "data_addrs": [0x4614], "palette_offset": 0x0658b9},
    "MadSciensteinGfx": {"gfx_addr": 0x53a5, "data_addrs": [0x4574], "palette_offset": 0x065729},
    "MizuuoGfx": {"gfx_addr": 0x45a5, "data_addrs": [0x44fc], "palette_offset": 0x06555e},
    "OwlGfx": {"gfx_addr": 0x650e, "data_addrs": [0x461c], "palette_offset": 0x065b58},
    "SilkyGfx": {"gfx_addr": 0x490d, "data_addrs": [0x4514], "palette_offset": 0x065496},
    "SnakeGfx": {"gfx_addr": 0x4c59, "data_addrs": [0x452c], "palette_offset": 0x065628},
    "SpearheadGfx": {"gfx_addr": 0x4000, "data_addrs": [0x446c], "palette_offset": 0x065463},
}

SLOT_1_PACKAGES = {
    "ApplebyGfx": {"gfx_addr": 0x4e29, "data_addrs": [0x4534], "palette_offset": 0x0656c9},
    "CountRichtertoffenGfx": {"gfx_addr": 0x4327, "data_addrs": [0x44b4], "palette_offset": 0x065438},
    "HammerBotGfx": {"gfx_addr": 0x514c, "data_addrs": [0x4564], "palette_offset": 0x0656fc},
    "KushimushiGfx": {"gfx_addr": 0x4956, "data_addrs": [0x44ec, 0x44f4], "palette_offset": 0x065539},
    "ParaGoomGfx": {"gfx_addr": 0x4637, "data_addrs": [0x44c4], "palette_offset": 0x065630},
    "PneumoGfx": {"gfx_addr": 0x547a, "data_addrs": [0x4584], "palette_offset": 0x065764},
    "WebberGfx": {"gfx_addr": 0x4000, "data_addrs": [0x447c], "palette_offset": 0x065696},
}

SLOT_2_PACKAGES = {
    "DoughnuteerGfx": {"gfx_addr": 0x45b3, "data_addrs": [0x44cc], "palette_offset": 0x065440},
    "FireGfx": {"gfx_addr": 0x65ac, "data_addrs": [0x475c, 0x459c], "palette_offset": 0x066166},
    "HandGfx": {"gfx_addr": 0x567b, "data_addrs": [0x45cc], "palette_offset": 0x065869},
    "HebariiGfx": {"gfx_addr": 0x4327, "data_addrs": [0x44bc], "palette_offset": 0x065fcc},
    "KobattoGfx": {"gfx_addr": 0x545b, "data_addrs": [0x45c4], "palette_offset": 0x0658fc},
    "RockGfx": {"gfx_addr": 0x6502, "data_addrs": [0x454c], "palette_offset": 0x066331},
    "SpearBotGfx": {"gfx_addr": 0x4dc2, "data_addrs": [0x45a4], "palette_offset": 0x065704},
    "TadpoleGfx": {"gfx_addr": 0x62cc, "data_addrs": [0x471c], "palette_offset": 0x065fff},
    "ZombieGfx": {"gfx_addr": 0x4a8a, "data_addrs": [0x4594], "palette_offset": 0x06566b},
}

SLOT_3_PACKAGES = {
    "BeamBotGfx": {"gfx_addr": 0x4610, "data_addrs": [0x45ac], "palette_offset": 0x065448},
    "BrrrBearGfx": {"gfx_addr": 0x54ea, "data_addrs": [0x45dc], "palette_offset": 0x065b08},
    "FireBotGfx": {"gfx_addr": 0x4234, "data_addrs": [0x459c], "palette_offset": 0x065640},
    "NobiiruGfx": {"gfx_addr": 0x5dec, "data_addrs": [0x46cc, 0x46d4], "palette_offset": 0x065a0b},
    "TeruteruGfx": {"gfx_addr": 0x4ee3, "data_addrs": [0x456c], "palette_offset": 0x065741},
    "TorchGfx": {"gfx_addr": 0x4000, "data_addrs": [0x4484], "palette_offset": 0x06547b},
    "WaterDropGfx": {"gfx_addr": 0x5d44, "data_addrs": [0x46b4], "palette_offset": 0x065904},
}
