"""Enemy registry — auto-generated by tools/build_enemy_registry.py.

Each SLOT_N_PACKAGES entry:
  gfx_label: (data_labels, palette_rom_offset_in_hacked_rom)

gfx/data labels are resolved at generation time via warioland3.sym
(embedded elsewhere). The palette offset points into the hacked ROM
(vanilla ROM + bsdiff); the apworld reads 8 bytes from there at gen
time, so no vanilla palette bytes are shipped with the apworld.
"""

SLOT_0_PACKAGES = {
    "HaridamaGfx": {"gfx_addr": 0x624a, "data_addrs": [0x4604], "palette_offset": 0x0658a9},
    "MadSciensteinGfx": {"gfx_addr": 0x53a5, "data_addrs": [0x4564], "palette_offset": 0x065719},
    "MizuuoGfx": {"gfx_addr": 0x45a5, "data_addrs": [0x44ec], "palette_offset": 0x06554e},
    "OwlGfx": {"gfx_addr": 0x650e, "data_addrs": [0x460c], "palette_offset": 0x065b48},
    "SilkyGfx": {"gfx_addr": 0x490d, "data_addrs": [0x4504], "palette_offset": 0x065486},
    "SnakeGfx": {"gfx_addr": 0x4c59, "data_addrs": [0x451c], "palette_offset": 0x065618},
    "SpearheadGfx": {"gfx_addr": 0x4000, "data_addrs": [0x445c], "palette_offset": 0x065453},
}

SLOT_1_PACKAGES = {
    "ApplebyGfx": {"gfx_addr": 0x4e29, "data_addrs": [0x4524], "palette_offset": 0x0656b9},
    "CountRichtertoffenGfx": {"gfx_addr": 0x4327, "data_addrs": [0x44a4], "palette_offset": 0x065428},
    "HammerBotGfx": {"gfx_addr": 0x514c, "data_addrs": [0x4554], "palette_offset": 0x0656ec},
    "KushimushiGfx": {"gfx_addr": 0x4956, "data_addrs": [0x44dc, 0x44e4], "palette_offset": 0x065529},
    "ParaGoomGfx": {"gfx_addr": 0x4637, "data_addrs": [0x44b4], "palette_offset": 0x065620},
    "PneumoGfx": {"gfx_addr": 0x547a, "data_addrs": [0x4574], "palette_offset": 0x065754},
    "WebberGfx": {"gfx_addr": 0x4000, "data_addrs": [0x446c], "palette_offset": 0x065686},
}

SLOT_2_PACKAGES = {
    "DoughnuteerGfx": {"gfx_addr": 0x45b3, "data_addrs": [0x44bc], "palette_offset": 0x065430},
    "FireGfx": {"gfx_addr": 0x65ac, "data_addrs": [0x474c, 0x458c], "palette_offset": 0x066156},
    "HandGfx": {"gfx_addr": 0x567b, "data_addrs": [0x45bc], "palette_offset": 0x065859},
    "HebariiGfx": {"gfx_addr": 0x4327, "data_addrs": [0x44ac], "palette_offset": 0x065fbc},
    "KobattoGfx": {"gfx_addr": 0x545b, "data_addrs": [0x45b4], "palette_offset": 0x0658ec},
    "RockGfx": {"gfx_addr": 0x6502, "data_addrs": [0x453c], "palette_offset": 0x066321},
    "SpearBotGfx": {"gfx_addr": 0x4dc2, "data_addrs": [0x4594], "palette_offset": 0x0656f4},
    "TadpoleGfx": {"gfx_addr": 0x62cc, "data_addrs": [0x470c], "palette_offset": 0x065fef},
    "ZombieGfx": {"gfx_addr": 0x4a8a, "data_addrs": [0x4584], "palette_offset": 0x06565b},
}

SLOT_3_PACKAGES = {
    "BeamBotGfx": {"gfx_addr": 0x4610, "data_addrs": [0x459c], "palette_offset": 0x065438},
    "BrrrBearGfx": {"gfx_addr": 0x54ea, "data_addrs": [0x45cc], "palette_offset": 0x065af8},
    "FireBotGfx": {"gfx_addr": 0x4234, "data_addrs": [0x458c], "palette_offset": 0x065630},
    "NobiiruGfx": {"gfx_addr": 0x5dec, "data_addrs": [0x46bc, 0x46c4], "palette_offset": 0x0659fb},
    "TeruteruGfx": {"gfx_addr": 0x4ee3, "data_addrs": [0x455c], "palette_offset": 0x065731},
    "TogebaGfx": {"gfx_addr": 0x5861, "data_addrs": [0x45fc], "palette_offset": 0x065ac5},
    "TorchGfx": {"gfx_addr": 0x4000, "data_addrs": [0x4474], "palette_offset": 0x06546b},
    "WaterDropGfx": {"gfx_addr": 0x5d44, "data_addrs": [0x46a4], "palette_offset": 0x0658f4},
}
