"""Auto-generated by tools/build_manual_throwable_config.py from
tools/manual_throw_block_rooms.json. The JSON is the player's
hand-verified list of throw-block room requirements; this module
is what the enemizer actually reads.

Regenerate after every edit to manual_throw_block_rooms.json:
    python tools/build_manual_throwable_config.py
"""

# Single-slot cases: enemizer forces a throwable into this slot
# for the wgid. All non-forced slots randomize freely.
MANUAL_TB_WGID_SLOT: dict = {
    0x01: 0,
    0x0a: 0,
    0x0b: 2,
    0x0d: 1,
    0x0e: 0,
    0x12: 2,
    0x16: 0,
    0x29: 0,
    0x33: 1,
    0x44: 1,
    0x46: 2,
    0x49: 3,
    0x5c: 0,
    0x62: 3,
    0x6d: 3,
    0x71: 0,
    0x73: 3,
    0x7a: 0,
    0x80: 3,
    0x89: 1,
}

# Multi-slot cases: enemizer keeps the vanilla ObjectGroup so
# both required throwables survive.
MANUAL_FORCE_VANILLA_WGIDS: set = {
    0x23,
    0x28,
    0x86,
}

# Every wgid the player marked (including "none" entries).
# Wgids NOT in this set fall back to auto-detected behaviour.
MANUAL_MARKED_WGIDS: set = {
    0x01,
    0x0a,
    0x0b,
    0x0d,
    0x0e,
    0x12,
    0x16,
    0x23,
    0x28,
    0x29,
    0x33,
    0x3c,
    0x44,
    0x46,
    0x49,
    0x5c,
    0x62,
    0x6d,
    0x71,
    0x73,
    0x7a,
    0x80,
    0x86,
    0x89,
}

# Wgids the player explicitly said DO NOT need a throwable.
MANUAL_NO_THROWABLE_WGIDS: set = {
    0x3c,
}
