# AUTO-GENERATED by tools/build_text_variants.py — do not edit by hand.
# Regenerate after `make` if any variant .txt files change.

# Each entry: (label, compressed RLE bytes). rom.py picks one at random
# per seed and writes it over the vanilla blob at the target ROM offset.
# Variants shorter than the vanilla slot are padded with $00 (the RLE
# decompressor terminator), so leftover bytes are ignored at runtime.

# --- RUDY_PRE_FIGHT (9 variants) ---
RUDY_PRE_FIGHT = [
    # v01 (49 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f 88 54 6d 6e 7e "
        "6c 60 72 22 38 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 06 7f "
        "00"
    ),
    # v02 (70 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f 8d 53 67 68 6d "
        "6a 7e 6e 74 73 72 68 63 64 03 7f 8d 73 67 64 7e 6c 74 72 68 62 7e 61 6e "
        "77 23 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 06 7f 00"
    ),
    # v03 (94 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f 8c 56 67 60 73 "
        "7e 63 68 63 7e 78 6e 74 04 7f 8d 65 68 6d 63 7e 60 73 7e 40 61 6e 75 64 "
        "03 7f 8f 73 67 64 7e 42 6b 6e 74 63 72 7e 46 71 64 78 11 7f 86 42 67 64 "
        "72 73 22 3a 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 45 7f 00"
    ),
    # v04 (82 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f 9d 56 60 68 73 "
        "7e 78 6e 74 7e 6c 64 60 6d 7e 48 7f 62 60 6d 7e 73 71 60 6d 72 65 6e 71 "
        "6c 03 7f 89 60 6d 78 76 67 64 71 64 22 17 7f 81 5d 7f 7f 7f 7f 7f 7f 7f "
        "7f 7f 7f 7f 7f 7f 7f 06 7f 00"
    ),
    # v05 (91 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f aa 53 67 64 71 "
        "64 3a 72 7e 60 7e 67 68 63 63 64 6d 6f 60 73 67 7e 68 6d 7e 4e 74 73 7e "
        "6e 65 7f 7f 73 67 64 7e 56 6e 6e 63 72 22 16 7f 87 56 67 64 71 64 22 22 "
        "39 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 45 7f 00"
    ),
    # v06 (120 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f b0 53 67 60 6d "
        "6a 72 7e 65 6e 71 7e 73 67 64 7f 7f 6c 74 72 68 62 7e 61 6e 77 64 72 3c "
        "7e 6d 6e 76 48 3a 6c 7e 6e 65 65 7e 73 6e 7e 72 73 64 60 6b 10 7f 8c 4c "
        "64 66 60 75 68 73 60 6c 68 6d 72 04 7f 8f 65 71 6e 6c 7e 43 71 3b 7e 4c "
        "60 71 68 6e 21 21 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 45 7f 00"
    ),
    # v07 (55 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f 8e 45 6b 64 63 "
        "7e 45 71 68 6d 72 73 6e 6d 64 32 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f "
        "7f 7f 7f 7f 06 7f 00"
    ),
    # v08 (78 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f a5 48 7e 73 71 "
        "68 64 63 7e 73 6e 7e 62 60 73 62 67 72 6e 6c 64 7e 65 6e 66 3c 7e 61 74 "
        "73 7e 48 7f 6c 68 72 73 3b 1b 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f "
        "7f 7f 7f 06 7f 00"
    ),
    # v09 (103 bytes)
    bytes.fromhex(
        "90 40 7e 67 68 63 63 64 6d 7f 65 68 66 74 71 64 00 30 7f 8c 56 64 7e 60 "
        "6b 6b 7e 65 6b 6e 60 73 04 7f 89 63 6e 76 6d 7e 67 64 71 64 03 3b 04 7f "
        "8c 4f 71 64 72 72 7e 52 64 6b 64 62 73 14 7f 8d 60 6d 63 7e 54 6f 7e 6e "
        "6d 7e 73 67 64 03 7f 84 43 6f 60 63 2c 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f "
        "7f 7f 7f 7f 45 7f 00"
    ),
]

# --- OLD_MAN_THANK_YOU (6 variants) ---
OLD_MAN_THANK_YOU = [
    # v01 (79 bytes)
    bytes.fromhex(
        "88 4e 6b 63 7e 4c 60 6d 00 38 7f ae 48 7e 74 72 64 63 7e 73 6e 7e 67 60 "
        "73 64 7f 7f 65 60 62 68 60 6b 7e 67 60 68 71 3c 7e 61 74 73 68 73 7e 66 "
        "71 64 76 7e 6e 6d 7e 6c 64 3b 12 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f "
        "7f 7f 7f 7f 06 7f 00"
    ),
    # v02 (128 bytes)
    bytes.fromhex(
        "88 4e 6b 63 7e 4c 60 6d 00 38 7f ae 56 60 68 73 7e 76 64 7e 60 71 64 7e "
        "68 6d 7f 7f 60 7e 6c 74 72 68 62 7e 61 6e 77 22 7e 40 71 64 78 6e 74 7e "
        "73 64 6b 6b 68 6d 66 7e 6c 64 12 7f 8d 73 67 68 72 7e 76 60 72 7e 72 6e "
        "6c 64 03 7f a0 72 6e 71 73 7e 6e 65 7e 56 60 71 68 6e 3a 72 7f 6b 60 63 "
        "63 64 71 7e 72 62 64 6d 60 71 68 6e 22 10 7f 81 5d 7f 7f 7f 7f 7f 7f 7f "
        "7f 7f 7f 7f 7f 45 7f 00"
    ),
    # v03 (117 bytes)
    bytes.fromhex(
        "88 4e 6b 63 7e 4c 60 6d 00 38 7f b0 40 6b 6b 7e 6e 65 7e 73 67 64 7e 6f "
        "6e 76 64 71 51 74 63 78 7e 72 73 6e 6b 64 7e 62 60 6c 64 7f 65 71 6e 6c "
        "7e 6c 78 7e 6c 74 72 73 60 62 67 64 10 7f 8d 53 67 60 6d 6a 7e 78 6e 74 "
        "7e 65 6e 71 03 7f 93 71 64 73 74 71 6d 68 6d 66 7e 68 73 7e 73 6e 7f 6c "
        "64 21 1d 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 45 7f 00"
    ),
    # v04 (77 bytes)
    bytes.fromhex(
        "88 4e 6b 63 7e 4c 60 6d 00 38 7f 99 40 6b 6b 7e 51 74 63 78 7e 6f 6e 76 "
        "64 71 7f 7f 76 60 72 7e 68 6d 7e 6c 78 07 7f 90 6c 74 72 73 60 62 67 64 "
        "3b 7e 53 67 60 6d 6a 72 10 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f "
        "7f 7f 06 7f 00"
    ),
    # v05 (72 bytes)
    bytes.fromhex(
        "88 4e 6b 63 7e 4c 60 6d 00 38 7f a7 56 67 60 73 7e 63 6e 7e 78 6e 74 7e "
        "6c 64 60 6d 6e 6b 63 7e 6c 60 6d 22 22 7e 48 7e 67 60 75 64 60 7e 6d 60 "
        "6c 64 21 19 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 06 7f 00"
    ),
    # v06 (75 bytes)
    bytes.fromhex(
        "88 4e 6b 63 7e 4c 60 6d 00 38 7f 88 4b 6e 6d 66 7e 60 66 6e 03 3b 8f 7e "
        "61 6b 60 67 61 6b 60 67 7e 61 6b 60 67 3b 06 7f 8d 4b 64 73 3a 72 7e 6f "
        "60 71 73 78 21 21 13 7f 81 5d 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f "
        "06 7f 00"
    ),
]

