"""Auto-generated by tools/build_throw_block_flags.py.

Do NOT edit by hand. Re-run the tool if throw_block_rooms.py
or level_constants.asm changes.

Key: (owlevel_1_based, wRoom_byte_value)
Value: auto-detected vanilla throwable VRAM slot (0-3) or None
       (throw block present but no vanilla throwable identified).
Absence from the dict means the auto-scanner did NOT flag this
(level, room) as containing a throw block.
"""

THROW_BLOCK_AUTO_FLAGS: dict = {
    ( 1, 0x01): 0,
    ( 1, 0x02): 0,
    ( 1, 0x03): 0,
    ( 1, 0x04): 0,
    ( 4, 0x13): 0,
    ( 5, 0x14): 2,
    ( 5, 0x15): 0,
    ( 5, 0x71): 0,
    ( 5, 0x72): 0,
    ( 5, 0x73): 2,
    ( 7, 0x18): 0,
    ( 7, 0x3E): 2,
    ( 8, 0x15): 0,
    (10, 0x1F): 1,
    (10, 0x20): 2,
    (10, 0x3A): 0,
    (10, 0x54): 1,
    (10, 0x55): 2,
    (10, 0x57): 0,
    (11, 0x22): None,
    (11, 0x36): 0,
    (11, 0x37): 0,
    (11, 0x7B): None,
    (11, 0x7C): None,
    (11, 0x7D): None,
    (11, 0x7E): None,
    (11, 0x7F): None,
    (12, 0x30): 0,
}
